const LOAD_SINGLE_USER = 'LOAD_SINGLE_USER';
const LOAD_USERS = 'LOAD_USERS';
const LOAD_POSTS = 'LOAD_POSTS';
const LOAD_COMMENTS= 'LOAD_COMMENTS';

export {
    LOAD_SINGLE_USER,
    LOAD_USERS,
    LOAD_POSTS,
    LOAD_COMMENTS
}
